### ISSUE TITLE
PHP Error on 'My teams'

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#10]
As follows on the picture:
<img width="529" alt="Captura de pantalla 2021-06-01 a las 16 36 48" src="https://user-images.githubusercontent.com/24532683/120341974-a7089400-c2f7-11eb-8af7-2185d68bbe48.png">

**Comment by symlinktech** [comment]
Please check and let us know if there are any mistakes.

**Comment by guille10k** [comment]
Good now. Closing
