### ISSUE TITLE
More substitutions errors

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#17]
The team leading on Saturday, after making substitutions, had more value than the limit, and anyways was participating and complete. 

![WhatsApp Image 2021-06-19 at 18 16 35](https://user-images.githubusercontent.com/24532683/122648829-351faf80-d12b-11eb-9079-7599f2854c73.jpeg)

**Comment by symlinktech** [comment]
If a user makes a board substitution in the team, then the value of the new boat is captured by the team.
Please check

**Comment by guille10k** [comment]
Fine, thank you.
