### ISSUE TITLE
Deactivating teams

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#18]
What does it do? Apparently nothing, but it would be good to deactivate teams from there (not able to participate).

In admin/teams

<img width="256" alt="Captura de pantalla 2021-06-19 a las 18 22 45" src="https://user-images.githubusercontent.com/24532683/122648892-757f2d80-d12b-11eb-89ad-e1ae8a7bbae6.png">

**Comment by symlinktech** [comment]
https://www.loom.com/share/6c641f6030a444249581b33df645d2aa

**Comment by guille10k** [comment]
Perfect. Closing this issue. Thanks
