### ISSUE TITLE
Little design change

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#19]
It would be better to put the old boats under substitution board instead of the new ones. The new ones along the rest of the team.

![3e9c5f41-5e9f-4ff1-beff-74444f0f79cc](https://user-images.githubusercontent.com/24532683/122672258-e6c1ed80-d1ca-11eb-8897-443e5a5beb85.jpg)

**Comment by symlinktech** [comment]
Please check and let us know if it's okay.

**Comment by guille10k** [comment]
Still the same, right? what has it changed? 

<img width="751" alt="Captura de pantalla 2021-07-09 a las 8 06 45" src="https://user-images.githubusercontent.com/24532683/125001063-bf08cb80-e08c-11eb-9c68-d79aa686aee3.png">

On the top part, the boats that are still giving points to the team. On the bottom part, those who doesn't give points anymore because are not in the team.

**Comment by symlinktech** [comment]
Please Check

**Comment by guille10k** [comment]
Perfect
