### ISSUE TITLE
Change message when no leagues are coming

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#20]
Change this message to something like "Ooops, no upcoming games yet! Try later."

<img width="879" alt="Captura de pantalla 2021-07-09 a las 8 16 48" src="https://user-images.githubusercontent.com/24532683/125001665-283d0e80-e08e-11eb-8adb-af12c4ba9da6.png">

**Comment by symlinktech** [comment]
Please check it.

**Comment by guille10k** [comment]
Perfect, thanks. 

Closing.
