### ISSUE TITLE
Email user name substitution

### ISSUE THREAD

**Issue by GPaddle** [guille10k/slalomManagerWeb#21]
The mail template looks broken, it doesn't replace the user name 😉 instead we have 

Hi {User_name}

Maybe a $ is missing ? Or if its a Tpl file, a problem to get data

**Comment by symlinktech** [comment]
https://www.loom.com/share/ac17d90c77714d5bb8ed5aaa2183b546

**Comment by guille10k** [comment]
Ok, thank you.
