### ISSUE TITLE
On substitution history, boat name missing link

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#4]
Names on substitution history should be a link to boat profile modal

<img width="362" alt="Captura de pantalla 2021-05-29 a las 18 27 18" src="https://user-images.githubusercontent.com/24532683/120077613-8fd56680-c0ab-11eb-9937-c1c374bd3c45.png">

**Comment by symlinktech** [comment]
Please check and let us know if it's okay.

**Comment by guille10k** [comment]
Not working

**Comment by symlinktech** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/47890547/120202166-e70e3f00-c243-11eb-9dc8-610a723ad73f.png)

**Comment by guille10k** [comment]
Not working. I click on the name Jana DUKATOVA and nothing happens. The modal with athlete profile should open.

**Comment by symlinktech** [comment]
Please check

**Comment by guille10k** [comment]
Working perfectly. I close this issue.
