### ISSUE TITLE
Void stats when clicking on team STATS

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#5]
When a league has more than one round, Team detail show nothing. It should show by default, the stats of the last round completed

<img width="761" alt="Captura de pantalla 2021-05-29 a las 18 30 28" src="https://user-images.githubusercontent.com/24532683/120077690-f35f9400-c0ab-11eb-9476-63406e5ba9f5.png">

**Comment by symlinktech** [comment]
Please check and let us know if it's okay.

**Comment by guille10k** [comment]
Perfect! I close this issue.
