### ISSUE TITLE
Total team points on Team stats

### ISSUE THREAD

**Issue by guille10k** [guille10k/slalomManagerWeb#6]
<img width="725" alt="Captura de pantalla 2021-05-30 a las 9 29 16" src="https://user-images.githubusercontent.com/24532683/120096060-a0c4bd00-c129-11eb-9241-93bae6274eaa.png">

**Comment by symlinktech** [comment]
Please check.

**Comment by guille10k** [comment]
Good.

Maybe this row in different color (light grey) and with also total points for every round?

**Comment by symlinktech** [comment]
Please check and let us know if it's okay.

**Comment by guille10k** [comment]
The color row is perfect. Do you think you can add the total points on every column? R1, R2...

**Comment by symlinktech** [comment]
Please check and let us know if it's okay.

**Comment by guille10k** [comment]
Perfect now, thank you very much.

Closing issue.
